<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title><?php echo $title; ?></title>

	<?php foreach($meta_tags as $tag => $value) : ?>
	<meta name="<?php echo $tag; ?>" content="<?php echo $value; ?>">
	<?php endforeach; ?>

	<meta name="viewport" content="width=device-width,initial-scale=1">

	<link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico'); ?>">
	<link rel="apple-touch-icon" href="<?php echo Core\Asset::getFile('apple-touch-icon.png', 'img'); ?>">
	<link rel="apple-touch-icon" sizes="72x72" href="<?php echo Core\Asset::getFile('apple-touch-icon-72x72-precomposed.png', 'img'); ?>">
	<link rel="apple-touch-icon" sizes="114x114" href="<?php echo Core\Asset::getFile('apple-touch-icon-114x114-precomposed.png', 'img'); ?>">
	<?php echo Core\Asset::render('layout'); ?>
	<?php echo Core\Asset::instance('theme')->render('layout'); ?>
	<?php echo Core\Asset::render('inline', true); ?>
	<?php echo Core\Asset::instance('theme')->render('inline', true); ?>
</head>
<body>

	<?php echo $body; ?>

	<?php if($gaq_id !== null) : ?>
	<script>
		var _gaq=[['_setAccount','<?php echo $gaq_id; ?>'],['_trackPageview']];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
	<?php endif; ?>

	<!--[if lt IE 7 ]>
		<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
		<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
	<![endif]-->

</body>
</html>