<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title><?php echo $this->title; ?></title>

		<meta name="viewport" content="width=device-width,initial-scale=1" />

		<link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico'); ?>" />
		<link rel="apple-touch-icon" href="<?php echo Core\Asset::getFile('apple-touch-icon.png', 'img'); ?>" />
		<link rel="apple-touch-icon" sizes="72x72" href="<?php echo Core\Asset::getFile('apple-touch-icon-72x72-precomposed.png', 'img'); ?>" />
		<link rel="apple-touch-icon" sizes="114x114" href="<?php echo Core\Asset::getFile('apple-touch-icon-114x114-precomposed.png', 'img'); ?>" />
		<?php echo Core\Asset::render(); ?>
		<?php if(Core\Asset::getInstance('theme')) echo Core\Asset::getInstance('theme')->render(); ?><!--/assets -->
	</head>
	<body>

		<!-- content --><?php echo $this->content; ?><!-- /content -->

		<!--[if lt IE 7 ]>
			<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
			<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
		<![endif]-->

	</body>
</html>