<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><?= $title ?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Assets -->
		<?= Core\Asset::getInstance()->render() ?>
		<?= Core\Asset::getInstance('theme') and Core\Asset::getInstance('theme')->render() ?>

		<!-- Assets -->

		<style type="text/css">
			body {
				padding-top: 60px;
				padding-bottom: 40px;
			}

			section {
				padding-top: 60px;
			}

			.btn-extra-large {
				border-radius: 6px 6px 6px 6px;
				font-size: 20px;
				font-weight: normal;
				margin-right: 10px;
				padding: 14px 24px;
			}
			#torneio {
				margin: 60px 0;
				padding: 40px 0;
				border-radius: 7px;
				text-align: center;
				background-color: #f0f1f1;
			}

			#torneio h1 {
				font-size: 41px;
				line-height: 41px;
				letter-spacing: -1px;
			}
		</style>

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<script type="text/javascript">
			$(function(){
				//$('.nav-collapse').scrollspy();
			});
		</script>
	</head>

	<body data-spy="scroll">

		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="#">MBC 2012</a>
					<div class="nav-collapse">
						<ul class="nav">
							<li class="active"><a href="#torneio">Torneio</a></li>
							<li><a href="#info">Informações</a></li>
							<li><a href="#cadastro">Cadastro</a></li>
						</ul>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>

		<div class="container">

			<?= $content ?>

			<hr>

			<footer>
				<p>&copy; mbRO 2012</p>
			</footer>

		</div> <!-- /container -->

	</body>
</html>